# Generated by Django 5.2.9 on 2025-12-03 07:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccommodationOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, verbose_name='订单ID')),
                ('check_in_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='入住时间')),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='退房时间')),
                ('status', models.CharField(choices=[('active', '入住中'), ('completed', '已退房'), ('cancelled', '已取消')], default='active', max_length=20, verbose_name='订单状态')),
                ('room_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='房费')),
            ],
            options={
                'verbose_name': '入住订单',
                'verbose_name_plural': '入住订单',
                'db_table': 'accommodation_order',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='房间号')),
                ('room_type', models.CharField(choices=[('standard', '标准间'), ('deluxe', '豪华间'), ('suite', '套房')], default='standard', max_length=20, verbose_name='房间类型')),
                ('status', models.CharField(choices=[('available', '空闲'), ('occupied', '已入住'), ('maintenance', '维护中')], default='available', max_length=20, verbose_name='房间状态')),
                ('price_per_day', models.DecimalField(decimal_places=2, default=400, max_digits=10, verbose_name='每日房价')),
            ],
            options={
                'verbose_name': '房间',
                'verbose_name_plural': '房间',
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False, verbose_name='顾客ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('id_card', models.CharField(max_length=18, verbose_name='身份证号')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '顾客',
                'verbose_name_plural': '顾客',
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='StatisticsReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False, verbose_name='报表ID')),
                ('report_type', models.CharField(choices=[('daily', '日报表'), ('weekly', '周报表'), ('monthly', '月报表')], max_length=20, verbose_name='报表类型')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('total_rooms_used', models.IntegerField(default=0, verbose_name='使用房间数')),
                ('total_energy', models.FloatField(default=0, verbose_name='总耗电量(度)')),
                ('total_ac_income', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='空调收入')),
                ('total_room_income', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='房费收入')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '统计报表',
                'verbose_name_plural': '统计报表',
                'db_table': 'statistics_report',
            },
        ),
        migrations.CreateModel(
            name='AccommodationBill',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False, verbose_name='账单ID')),
                ('room_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='房费')),
                ('ac_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='空调费')),
                ('total_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='总费用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_paid', models.BooleanField(default=False, verbose_name='是否已支付')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ac_system.accommodationorder', verbose_name='关联订单')),
            ],
            options={
                'verbose_name': '住宿账单',
                'verbose_name_plural': '住宿账单',
                'db_table': 'accommodation_bill',
            },
        ),
        migrations.CreateModel(
            name='ACState',
            fields=[
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ac_system.room', verbose_name='房间')),
                ('is_on', models.BooleanField(default=False, verbose_name='是否开机')),
                ('status', models.CharField(choices=[('off', '关机'), ('on', '开机'), ('standby', '待机')], default='off', max_length=20, verbose_name='空调状态')),
                ('mode', models.CharField(choices=[('cooling', '制冷'), ('heating', '制热')], default='cooling', max_length=20, verbose_name='模式')),
                ('current_temp', models.FloatField(default=25.0, verbose_name='当前温度')),
                ('target_temp', models.FloatField(default=25.0, verbose_name='目标温度')),
                ('fan_speed', models.CharField(choices=[('low', '低风'), ('medium', '中风'), ('high', '高风')], default='medium', max_length=10, verbose_name='风速')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='累计费用')),
                ('total_energy', models.FloatField(default=0, verbose_name='累计耗电量(度)')),
                ('service_start_time', models.DateTimeField(blank=True, null=True, verbose_name='服务开始时间')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '空调状态',
                'verbose_name_plural': '空调状态',
                'db_table': 'ac_state',
            },
        ),
        migrations.CreateModel(
            name='ACDetailRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False, verbose_name='详单ID')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('start_temp', models.FloatField(verbose_name='开始温度')),
                ('end_temp', models.FloatField(blank=True, null=True, verbose_name='结束温度')),
                ('target_temp', models.FloatField(verbose_name='目标温度')),
                ('fan_speed', models.CharField(max_length=10, verbose_name='风速')),
                ('mode', models.CharField(max_length=20, verbose_name='模式')),
                ('energy_consumed', models.FloatField(default=0, verbose_name='耗电量(度)')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='费用')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ac_system.accommodationorder', verbose_name='关联订单')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_system.room', verbose_name='房间')),
            ],
            options={
                'verbose_name': '空调使用详单',
                'verbose_name_plural': '空调使用详单',
                'db_table': 'ac_detail_record',
            },
        ),
        migrations.AddField(
            model_name='accommodationorder',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_system.room', verbose_name='房间'),
        ),
        migrations.CreateModel(
            name='ACBill',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False, verbose_name='账单ID')),
                ('total_energy', models.FloatField(default=0, verbose_name='总耗电量(度)')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='总费用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_system.accommodationorder', verbose_name='关联订单')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_system.room', verbose_name='房间')),
            ],
            options={
                'verbose_name': '空调账单',
                'verbose_name_plural': '空调账单',
                'db_table': 'ac_bill',
            },
        ),
        migrations.AddField(
            model_name='accommodationorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_system.customer', verbose_name='顾客'),
        ),
    ]
