# Generated by Django 5.2.9 on 2025-12-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_system', '0003_add_reservation_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='预定ID'),
        ),
    ]
