# Generated by Django 5.2.9 on 2025-12-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_system', '0005_accommodationbill_deposit_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='room',
        ),
        migrations.RemoveField(
            model_name='accommodationbill',
            name='deposit_amount',
        ),
        migrations.RemoveField(
            model_name='accommodationbill',
            name='meal_fee',
        ),
        migrations.RemoveField(
            model_name='accommodationorder',
            name='deposit_amount',
        ),
        migrations.RemoveField(
            model_name='accommodationorder',
            name='deposit_paid',
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', '空闲'), ('occupied', '已入住'), ('maintenance', '维护中')], default='available', max_length=20, verbose_name='房间状态'),
        ),
        migrations.DeleteModel(
            name='MealOrder',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
