# Generated by Django 5.2.9 on 2025-12-18 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_system', '0006_remove_reservation_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationbill',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='已收押金'),
        ),
        migrations.AddField(
            model_name='accommodationbill',
            name='meal_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='餐饮费'),
        ),
        migrations.AddField(
            model_name='accommodationorder',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='押金'),
        ),
        migrations.AddField(
            model_name='accommodationorder',
            name='deposit_paid',
            field=models.BooleanField(default=False, verbose_name='押金已收取'),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', '空闲'), ('reserved', '已预定'), ('occupied', '已入住'), ('maintenance', '维护中')], default='available', max_length=20, verbose_name='房间状态'),
        ),
        migrations.CreateModel(
            name='MealOrder',
            fields=[
                ('meal_id', models.AutoField(primary_key=True, serialize=False, verbose_name='餐饮订单ID')),
                ('items', models.TextField(verbose_name='菜品明细(JSON)')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='总金额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_system.accommodationorder', verbose_name='关联入住订单')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_system.room', verbose_name='房间')),
            ],
            options={
                'verbose_name': '餐饮订单',
                'verbose_name_plural': '餐饮订单',
                'db_table': 'meal_order',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False, verbose_name='预定ID')),
                ('name', models.CharField(max_length=50, verbose_name='预定人姓名')),
                ('phone', models.CharField(max_length=11, verbose_name='预定人手机号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='预定时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ac_system.room', verbose_name='房间')),
            ],
            options={
                'verbose_name': '房间预定',
                'verbose_name_plural': '房间预定',
                'db_table': 'reservation',
            },
        ),
    ]
