# Generated by Django 5.2.9 on 2025-12-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_system', '0007_accommodationbill_deposit_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationorder',
            name='power_on_count',
            field=models.IntegerField(default=0, verbose_name='空调开机次数'),
        ),
    ]
